# hash:sha256:7a8072cf7bb09ae53553493ffd180240106e9f8cea01491294ca52b116e3b87f
FROM registry.acmecorp-edge.codeocean.com/codeocean/bioinformatics:2.0.0

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
